### ISSUE TITLE
Weekly render sometimes fails

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/BxJS-Website#5]
Weekly render sometimes has following error:

```
TypeError: Cannot read property 'url' of undefined
    at /usr/src/app/.next/server/static/mrCX9iF_GNHUGgVV_nqc4/pages/weekly.js:1:29053
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at i (/usr/src/app/.next/server/static/mrCX9iF_GNHUGgVV_nqc4/pages/weekly.js:1:6664)
    at a (/usr/src/app/.next/server/static/mrCX9iF_GNHUGgVV_nqc4/pages/weekly.js:1:6858)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by yamalight** [comment]
No longer an issue
