### ISSUE TITLE
List of episodes can error out sometimes

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/BxJS-Website#9]

**Comment by yamalight** [comment]
Server restart seem to fix it

**Comment by yamalight** [comment]
Was failing with following error:
```
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 141)
(node:19) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token %
    at handleError (/usr/src/app/node_modules/fastify/lib/reply.js:414:3)
    at onErrorHook (/usr/src/app/node_modules/fastify/lib/reply.js:373:5)
    at _Reply.Reply.send (/usr/src/app/node_modules/fastify/lib/reply.js:98:5)
    at defaultErrorHandler (/usr/src/app/node_modules/fastify/fastify.js:733:11)
    at handleError (/usr/src/app/node_modules/fastify/lib/reply.js:401:18)
    at onErrorHook (/usr/src/app/node_modules/fastify/lib/reply.js:373:5)
    at _Reply.Reply.send (/usr/src/app/node_modules/fastify/lib/reply.js:98:5)
    at /usr/src/app/node_modules/fastify/lib/wrapThenable.js:43:11
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by yamalight** [comment]
No longer an issue
